use_frameworks!

platform :ios, '8.0'

target 'YXTemplate_Example' do
  pod 'YXTemplate', :path => '../'

  target 'YXTemplate_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
